import Reveal from './Reveal'
import AnimatedDetails from './AnimatedDetails'

const external = { target: '_blank', rel: 'noopener noreferrer' }
function Tags({ items }: { items: string[] }) { return <ul className="tags" aria-label="Technologies">{items.map(item => <li key={item}>{item}</li>)}</ul> }

export function Work() {
  return <section className="shell section" id="work" aria-labelledby="work-title">
    <Reveal className="section-heading"><div><p className="eyebrow section-number">01 / SELECTED WORK</p><h2 id="work-title">Built to solve.<br /><span>Designed to last.</span></h2></div><p>A selection of systems I’ve helped bring to life—from everyday operations to intelligent automation.</p></Reveal>
    <Reveal>
      <article className="featured-project">
        <div className="project-copy"><div className="project-kicker"><span>01</span><span>FULL-STACK / INTERNAL TOOLS</span></div><h3>EIS Client Database</h3><p>A connected workspace for client relationships and day-to-day operations at EIS Forensic. Built across the stack, from secure sign-in to production deployment.</p><Tags items={['React 19', 'TypeScript', '.NET 10', 'PostgreSQL']} /><AnimatedDetails className="project-details"><summary>Inside the engineering <span aria-hidden="true">+</span></summary><ul><li>Microsoft OAuth with domain-restricted sign-in and role-based access.</li><li>Test-driven development with Vitest and TUnit.</li><li>GitHub Actions for linting, testing, and Docker Compose deployment.</li></ul></AnimatedDetails><div className="project-meta"><span className="status-dot" /><span>Internal platform · May 2026–present</span></div></div>
        <div className="architecture" role="img" aria-label="EIS application architecture: React and TypeScript interface, Microsoft OAuth authentication, .NET API, and PostgreSQL database. GitHub Actions deploys through Docker Compose."><div className="diagram-label"><span>SYSTEM ARCHITECTURE</span><span aria-hidden="true">⌘</span></div><div className="architecture-flow"><div className="system-node ui-node"><span className="node-symbol" aria-hidden="true">{ '{ }' }</span><div><strong>React + TypeScript</strong><span>Client workspace</span></div><span className="node-port" /></div><div className="flow-connector" aria-hidden="true"><span /></div><div className="auth-label">Microsoft OAuth <span>↗</span> Role-based access</div><div className="system-node api-node"><span className="node-symbol" aria-hidden="true">#</span><div><strong>.NET API</strong><span>Application & business logic</span></div><span className="node-port" /></div><div className="flow-connector" aria-hidden="true"><span /></div><div className="system-node database-node"><span className="node-symbol" aria-hidden="true">≡</span><div><strong>PostgreSQL</strong><span>Persistent data</span></div><span className="node-port" /></div></div><div className="diagram-footer"><span>GitHub Actions</span><span aria-hidden="true">→</span><span>Docker Compose</span></div></div>
      </article>
    </Reveal>
    <div className="project-grid">
      <Reveal><article className="project-card"><div className="project-visual agent-visual"><div className="diagram-label"><span>02 / APPLIED AI</span><span>SPOTIFY AGENT</span></div><div className="agent-flow"><span className="agent-step">Your request</span><span className="flow-arrow" aria-hidden="true">↓</span><div className="agent-core"><span className="agent-glyph" aria-hidden="true">✳</span><span>Reason. Act. Observe.</span></div><span className="flow-arrow" aria-hidden="true">↓</span><span className="agent-step">Spotify tools + OAuth</span></div><p className="visual-caption">NATURAL LANGUAGE → REAL ACTIONS</p></div><div className="project-card-body"><h3>Spotify AI Agent</h3><p>A conversational assistant for playlists, discovery, and library organization. An agentic loop turns user intent into actions, with visibility and control throughout.</p><Tags items={['AI agents', 'OAuth', 'CI/CD']} /><div className="project-links"><a {...external} href="https://github.com/MateoTomaszeuski/spotify-manager-ai-agent">View source <span aria-hidden="true">↗</span></a><a {...external} href="https://spotify.mateo.tomaszeuski.com/">Visit project <span aria-hidden="true">↗</span></a></div></div></article></Reveal>
      <Reveal><article className="project-card"><div className="project-visual itin-visual"><div className="diagram-label"><span>03 / PRODUCT ENGINEERING</span><span>ITIN</span></div><div className="itin-wordmark" aria-hidden="true">itin<span>↗</span></div><div className="deployment-path"><div><span>01</span><strong>Build locally</strong><small>Docker</small></div><span aria-hidden="true">→</span><div><span>02</span><strong>Test together</strong><small>Kubernetes</small></div><span aria-hidden="true">→</span><div><span>03</span><strong>Ship to cloud</strong><small>Azure</small></div></div><p className="visual-caption">FROM FIRST IDEA TO NEXT ADVENTURE</p></div><div className="project-card-body"><h3>ITIN Trip Planner</h3><p>Turning travel ideas into organized itineraries. Full-stack development in a four-person Agile team, with Scrum Master experience and a path from local development to Azure.</p><Tags items={['C#', 'React', 'PostgreSQL', 'Azure']} /><div className="project-links"><a {...external} href="https://itin.tomaszeuski.com">Visit project <span aria-hidden="true">↗</span></a><span>Aug 2025–May 2026</span></div></div></article></Reveal>
    </div>
    <Reveal><AnimatedDetails className="project-archive"><summary><span>More explorations <small>Distributed systems, mobile & web</small></span><span className="details-plus" aria-hidden="true">+</span></summary><div className="archive-grid"><article><p className="eyebrow">DISTRIBUTED SYSTEMS / 2026</p><h3>2D Battle Royale</h3><p>A multiplayer game using Elixir, React, and PostgreSQL. Kubernetes and PubSub support multiple lobbies, pod failover, and database recovery.</p><a className="text-link" {...external} href="https://github.com/MateoTomaszeuski/2d-battle-royale-distributed-app">View source <span aria-hidden="true">↗</span></a></article><article><p className="eyebrow">MOBILE / 2025</p><h3>Consilium</h3><p>A student planner built with .NET MAUI, ASP.NET Core, and PostgreSQL. Developed in a four-person Agile team with structured usability testing.</p><div className="project-links"><a {...external} href="https://github.com/MateoTomaszeuski/consilium-student-planner-app">View source ↗</a><a {...external} href="https://consilium.mateo.tomaszeuski.com/">Visit project ↗</a></div></article><article><p className="eyebrow">WEB / 2024</p><h3>BMR & TDEE Calculator</h3><p>A Blazor web application with C# calculations and database persistence for user information.</p></article></div></AnimatedDetails></Reveal>
  </section>
}

const experience = [
  { date: 'AUG 2026 — PRESENT', company: 'DHI Computing Service, Inc.', title: 'Programmer/Analyst', location: 'Midvale, Utah', text: 'Developing full-stack banking applications for customer-facing platforms. Translating business and technical requirements into maintainable solutions for financial institutions.', items: ['C# / .NET', 'Angular', 'AI-assisted workflows'], current: true },
  { date: 'MAY 2026 — AUG 2026', company: 'EIS Forensic', title: 'Business Development & Technology Engineer Intern', location: 'Centerville, Utah', text: 'Built and deployed the company website, developed internal tools to streamline client communication, and integrated AI and CI/CD into engineering workflows.', items: ['React', 'ASP.NET Core', 'Automation'] },
  { date: 'SEP 2024 — MAY 2025', company: 'Dynamic Integrations', title: 'Software Engineering Intern', location: 'Ephraim, Utah', text: 'Worked with clients to refine requirements, used Docker for database testing, and presented software and technical decisions to customers and stakeholders.', items: ['Docker', 'Databases', 'Client collaboration'] },
]

export function Experience() {
  return <section className="experience-section" id="experience" aria-labelledby="experience-title"><div className="shell section">
    <Reveal className="section-heading"><div><p className="eyebrow section-number">02 / EXPERIENCE</p><h2 id="experience-title">Progress through<br /><span>practice.</span></h2></div><p>Building a stronger connection between engineering decisions and the people who depend on them.</p></Reveal>
    <div className="experience-list">{experience.map(job => <Reveal key={job.company}><article className={`experience-row ${job.current ? 'current-experience' : ''}`}><div className="experience-date"><span>{job.date}</span>{job.current && <span className="current-badge"><span className="status-dot" /> Current role</span>}</div><div className="experience-body"><p className="experience-company">{job.company}</p><h3>{job.title}</h3><p>{job.text}</p><Tags items={job.items} /></div><span className="experience-location">{job.location}</span></article></Reveal>)}</div>
    <AnimatedDetails className="community-details"><summary>Teaching & leadership at Snow College <span className="details-plus" aria-hidden="true">+</span></summary><div className="community-grid"><article><h3>Teaching & tutoring</h3><p>Software Engineering Teaching Assistant and Math Tutor · Aug 2025–May 2026</p><p>Supported .NET and ASP.NET Core labs, debugging, code reviews, mathematics, and statistics.</p></article><article><h3>Residential leadership</h3><p>Resident Director · Aug 2025–May 2026<br />Resident Assistant · Aug 2024–May 2025</p><p>Led resident assistants, organized meetings and activities, and supported student wellbeing.</p></article><article><h3>Student government</h3><p>Vice President · May–Dec 2023<br />Student Body Officer · Aug 2022–May 2023</p><p>Led marketing efforts, trained team members, and helped connect student feedback with campus initiatives.</p></article></div></AnimatedDetails>
  </div></section>
}

export function About() {
  return <section className="shell section about-section" id="about" aria-labelledby="about-title"><Reveal className="about-layout"><div><p className="eyebrow section-number">03 / BEYOND THE STACK</p><h2 id="about-title">An engineer.<br /><span>A people person.</span></h2><div className="about-photo"><img src="/professional.jpg" width="1086" height="1210" loading="lazy" alt="Mateo Tomaszeuski wearing a suit" /><span>From Argentina.<br />Building in Utah.</span></div></div><div className="about-copy"><p className="about-lead">Good software starts with understanding the people on the other side of the screen.</p><p>I’m Mateo, an Argentinian software engineer based in Utah. My work brings together full-stack development, applied AI, and the practical details of getting software into production.</p><p>Today, I build banking applications at DHI Computing Service. My background in client collaboration, teaching, and student leadership shapes how I work: ask good questions, communicate clearly, and take ownership from the first requirement to the final release.</p><div className="education"><span className="eyebrow">EDUCATION</span><h3>Bachelor’s in Software Engineering</h3><p>Snow College · 2022–2026</p><p>Associate’s in Computer Science · 2022–2024</p></div><div className="language-list"><span className="eyebrow">LANGUAGES</span><p>English · Spanish · Portuguese · German</p></div></div></Reveal><Reveal className="toolkit"><div><p className="eyebrow">THE TOOLKIT</p><h3>From interface<br />to infrastructure.</h3></div><dl><div><dt>Frontend</dt><dd>Angular · React · TypeScript · Blazor</dd></div><div><dt>Backend & data</dt><dd>C# · ASP.NET Core · PostgreSQL · Elixir</dd></div><div><dt>Cloud & delivery</dt><dd>Docker · Kubernetes · Azure · GitHub Actions</dd></div><div><dt>Intelligence & quality</dt><dd>AI agents · OAuth · Vitest · TUnit</dd></div></dl></Reveal></section>
}

export function Contact() {
  return <footer id="contact" className="contact-section"><div className="shell"><Reveal className="contact-main"><div><p className="eyebrow section-number">04 / GET IN TOUCH</p><h2>Good things start<br />with a <span>conversation.</span></h2><a className="email-link" href="mailto:mtomaszeuski@gmail.com">mtomaszeuski@gmail.com <span aria-hidden="true">↗</span></a></div><div className="contact-links"><a {...external} href="https://www.linkedin.com/in/mateo-tomaszeuski/">LinkedIn <span aria-hidden="true">↗</span></a><a {...external} href="https://github.com/MateoTomaszeuski">GitHub <span aria-hidden="true">↗</span></a><a href="/resume.pdf" download="Mateo Tomaszeuski - Resume.pdf">Résumé <span aria-hidden="true">↓</span></a></div></Reveal><div className="footer-bottom"><span>© {new Date().getFullYear()} Mateo Tomaszeuski</span><span>Built with care. Always evolving.</span><a href="#main">Back to top ↑</a></div></div></footer>
}
